### PR TITLE
dan's usa database

### PR DESCRIPTION
**Pull request by dmiller3830**
Added info and properties and compare and contrast

### CODE REVIEW

**Comment by wicamo96** [comment]
- Make sure your properties are spelled and formatted the same. (ex. line 11 is capitalized and the other population properties are not)
-Missing comma line 51, 72, etc...; make sure all of your properties in your objects are separated by commas
-Missing comma line 57, 76, etc...; make sure all of your objects in your database are separated by commas
-Lone quotation mark on 78
-No curly braces around landmark #3 
-Missing comma line 104; make sure your arrays in your database are separated by commas
-Surround all strings with quotation marks (ex line 133)

**Comment by wicamo96** [comment]
Looking better, still missing a couple commas separating some of your properties

**Comment by KathSchloe** [comment]
Looks good!

**Comment by wicamo96** [comment]
Looks good!

**Pull request merged**
